import React from 'react';
import Icon from '../index.tsx';

const list = [
  'accessible',
  'add-file',
  'add-list',
  'add-team',
  'add-user',
  'address-book',
  'android',
  'apple',
  'approval',
  'archive',
  'arrow-down',
  'arrow-left',
  'arrow-right',
  'arrow-right-circle',
  'arrow-up',
  'attention',
  'audio',
  'audio-file',
  'audio-fill',
  'audio-mute',
  'bearish',
  'behance',
  'bookmark',
  'branch',
  'briefcase',
  'broadcast',
  'brush',
  'brush-fill',
  'bullish',
  'business',
  'business-card',
  'calculator',
  'calendar',
  'callback',
  'cancel-file',
  'candle-sticks',
  'check-circle',
  'check-circle1',
  'check-file',
  'check-fill',
  'check-square',
  'checkmark',
  'chrome',
  'circle-share',
  'close',
  'close-circle',
  'close-fill',
  'cloud-download',
  'cloud-upload',
  'code',
  'collect',
  'colorlens',
  'comment',
  'comment-square',
  'conference',
  'copyright',
  'create-archive',
  'credit-card',
  'css',
  'currency-exchange',
  'cursor',
  'customer-service',
  'customer-support',
  'del-team',
  'del-user',
  'delete-archive',
  'delete-file',
  'delivered',
  'delivery',
  'department',
  'desktop',
  'diploma',
  'dislike',
  'doc',
  'document',
  'donate',
  'down',
  'down-arrow',
  'down-fill',
  'down-left-arrow',
  'down-left-round',
  'down-right-arrow',
  'down-right-round',
  'down-round',
  'download',
  'dropbox',
  'edit-file',
  'education',
  'expired',
  'external',
  'eye',
  'eye-close',
  'face',
  'facebook',
  'faq',
  'favourite-file',
  'feedback',
  'file',
  'file-zip',
  'fire',
  'fire-fill',
  'forbid',
  'fork',
  'gif',
  'gift',
  'github',
  'google',
  'hand-cursor',
  'heart',
  'heart-fill',
  'hierarchy',
  'home',
  'html',
  'id-card',
  'idea',
  'image-file',
  'info',
  'info-fill',
  'inspection',
  'instagram',
  'internal',
  'key',
  'laptop',
  'left',
  'left-arrow',
  'left-fill',
  'left-round',
  'library',
  'link',
  'linkedin',
  'lock',
  'loader',
  'loader-circle',
  'loader-quarter',
  'loader-3quarter',
  'login',
  'low-priority',
  'maintain',
  'manager',
  'medal',
  'medium',
  'medium-priority',
  'minus',
  'minus-circle',
  'minus-fill',
  'money-token',
  'money-transfer',
  'multiple-inputs',
  'music',
  'news',
  'no-idea',
  'note',
  'online-support',
  'open-archive',
  'opened-folder',
  'org-unit',
  'organization',
  'overtime',
  'package',
  'paid',
  'parking',
  'picture',
  'pie-chart',
  'play-fill',
  'plus',
  'plus-circle',
  'plus-fill',
  'privacy',
  'process',
  'projector',
  'psd',
  'puzzle',
  'qrcode',
  'question-fill',
  'questions',
  'rating',
  'reading',
  'redo',
  'registration-circle',
  'resize-all',
  'resize-diagonal',
  'resize-hr',
  'resize-ver',
  'right',
  'right-fill',
  'ruler',
  'scan',
  'search',
  'search-reverse',
  'setting',
  'settings',
  'share',
  'shop',
  'signature',
  'skin',
  'skype',
  'slack',
  'speaker',
  'split-horizontal',
  'split-vertical',
  'star',
  'star-fill',
  'statistics',
  'structure',
  'support',
  'survey',
  'switch',
  'switch-user',
  'sync',
  'tags',
  'team',
  'todo-list',
  'trademark',
  'trash',
  'twitter',
  'undo',
  'unlock',
  'up',
  'up-fill',
  'up-left-arrow',
  'up-left-round',
  'up-right-arrow',
  'up-right-round',
  'up-round',
  'upload',
  'user',
  'video-file',
  'view-file',
  'vip',
  'voice-person',
  'wallet',
  'warn-fill',
  'warning',
  'wechat',
  'weibo',
  'wifi',
  'word',
  'work',
  'xls',
  'youtube',
  'zoomin',
  'zoomout',
];

const IconList = (): JSX.Element => {
  return (
    <ul
      style={{
        listStyle: 'none',
        display: 'flex',
        flexWrap: 'wrap',
        padding: 0,
        margin: 0,
        borderTop: '1px solid #eaeefb',
        borderLeft: '1px solid #eaeefb',
      }}>
      {list.map((name) => (
        <li
          key={name}
          style={{
            width: '16.66%',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'center',
            color: '#454545',
            borderRight: '1px solid #eaeefb',
            borderBottom: '1px solid #eaeefb',
            padding: '20px 0',
          }}>
          <Icon name={name} size={30} />
          <span style={{ marginTop: 8 }}>{name}</span>
        </li>
      ))}
    </ul>
  );
};

export default IconList;
