import { withLocale } from './intl-provider/with-locale';

export { default as Affix } from './affix';
export { default as Alert } from './alert';
export { default as Avatar } from './avatar';
export { default as BackTop } from './backtop';
export { default as Badge } from './badge';
export { default as Button } from './button';
export { default as Carousel } from './carousel';
export { default as Checkbox } from './checkbox';
export { default as Col } from './col';
export { default as Collapse } from './collapse';
export { default as Countdown } from './countdown';
export { default as DatePicker } from './date-picker';
export { default as Divider } from './divider';
export { default as Flip } from './flip';
export { default as Form } from './form';
export { default as Icon } from './icon';
export { default as Input } from './input';
export { default as IntlProvider } from './intl-provider';
export { default as Layout } from './layout';
export { default as Loader } from './loader';
export { default as LoadingBar } from './loading-bar';
export { default as NativeSelect } from './select-native';
export { default as Row } from './row';
export { default as Modal } from './modal';
export { default as Overlay } from './overlay';
export { default as Popconfirm } from './popconfirm';
export { default as Popover } from './popover';
export { default as Progress } from './progress';
export { default as Radio } from './radio';
export { default as Switch } from './switch';
export { default as Textarea } from './textarea';
export { default as TimePicker } from './time-picker';
export { default as Typography } from './typography';
export { withLocale };
// export { default as Tooltip } from './tooltip';
